spring:
  profiles:
    active: loadInitialData
server:
  port: 9988

---

spring:
  config:
    activate:
      on-profile: loadInitialData
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true